---

- name: HAPROXY | HAProxy allowed in ufw
  community.general.ufw:
    proto: tcp
    rule: allow
    to_port: "{{ item }}"
  loop:
    - "{{ haproxy_http_port }}"
    - "{{ haproxy_https_port }}"
    - "{{ haproxy_stats_port }}"
  when: ansible_facts.os_family == "Debian"

- name: HAPROXY | HAProxy allowed in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: "{{ firewalld_zone }}"
    immediate: true
    permanent: true
    state: enabled
  loop:
    - "{{ haproxy_http_port }}/tcp"
    - "{{ haproxy_https_port }}/tcp"
    - "{{ haproxy_stats_port }}/tcp"
  when: ansible_facts.os_family == "RedHat"

- name: HAPROXY | Config directory created
  ansible.builtin.file:
    path: "{{ haproxy_config_dir }}/config_bind_mount"
    state: directory
    mode: "0750"

- name: HAPROXY | Environment file created
  ansible.builtin.file:
    path: "{{ haproxy_config_dir }}/haproxy.env"
    mode: "0640"
    state: touch
  changed_when: false

- name: HAPROXY | Certificate generated
  block:
    - name: HAPROXY | CERT | Private key generated
      community.crypto.openssl_privatekey:
        path: "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}.key"
        size: "{{ haproxy_cert_key_size }}"
        type: "{{ haproxy_cert_type }}"
        owner: "{{ podman_user }}"
        group: "{{ podman_user }}"
        mode: "0400"

    - name: HAPROXY | CERT | Check for cert
      ansible.builtin.stat:
        path: "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}"
      register: cert_path

    - name: HAPROXY | CERT | Cert generated
      community.crypto.x509_certificate:
        path: "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}"
        privatekey_path: "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}.key"
        provider: selfsigned
        owner: "{{ podman_user }}"
        group: "{{ podman_user }}"
        mode: "0400"
      register: cert_generated
      when: cert_path.stat.readable is not defined

    - name: HAPROXY | CERT | Private key concatenated to cert
      shell: >
         cat "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}.key" >>
         "{{ haproxy_config_dir }}/config_bind_mount/{{ haproxy_cert_filename }}"
      when: cert_generated.changed

- name: HAPROXY | Configuration file deployed
  ansible.builtin.template:
    src: haproxy/haproxy.cfg.j2
    dest: "{{ haproxy_config_dir }}/config_bind_mount/haproxy.cfg"
    mode: "0640"

# - name: HAPROXY | Check for systemd unit
#   ansible.builtin.stat:
#     path: /etc/systemd/system/podman-{{ haproxy_container_name }}.service
#   register: unit_file

# - name: HAPROXY | Container running (systemd)
#   systemd:
#     name: podman-{{ haproxy_container_name }}.service
#     state: started
#   when: unit_file.stat.exists is defined

- name: HAPROXY | Container running
  containers.podman.podman_container:
    name: "{{ haproxy_container_name }}"
    image: haproxy:latest
    env_file: "{{ haproxy_config_dir }}/haproxy.env"
    restart_policy: on-failure:5
    log_level: "{{ haproxy_log_level }}"
    log_driver: journald
    publish:
      - "{{ haproxy_http_port }}:{{ haproxy_http_port }}"
      - "{{ haproxy_https_port }}:{{ haproxy_https_port }}"
      - "{{ haproxy_stats_port }}:{{ haproxy_stats_port }}"
    ip: "{{ haproxy_internal_ip }}"
    volumes:
      - "{{ haproxy_config_dir }}/config_bind_mount:/usr/local/etc/haproxy"

- name: HAPROXY | Systemd config deployed
  include: systemd.yml
  vars:
    service: "{{ haproxy_container_name }}"
