---

- name: HEIMDALL | Config directory created
  ansible.builtin.file:
    path: "{{ heimdall_config_dir }}/config_bind_mount"
    state: directory
    mode: "0750"

# - name: HEIMDALL | Check for systemd unit
#   ansible.builtin.stat:
#     path: /etc/systemd/system/podman-{{ heimdall_container_name }}.service
#   register: unit_file

# - name: HEIMDALL | Container running (systemd)
#   systemd:
#     name: podman-{{ heimdall_container_name }}.service
#     state: started
#   when: unit_file.stat.exists is defined

- name: HEIMDALL | Container running
  containers.podman.podman_container:
    name: "{{ heimdall_container_name }}"
    image: linuxserver/heimdall:latest
    restart_policy: on-failure:5
    log_level: "{{ heimdall_log_level }}"
    log_driver: journald
    env:
      TZ: "{{ timezone }}"
    ip: "{{ heimdall_internal_ip }}"
    volumes:
      - "{{ heimdall_config_dir }}/config_bind_mount:/config"

- name: HAPROXY | Systemd config deployed
  include: systemd.yml
  vars:
    service: "{{ heimdall_container_name }}"
