---

- name: HEIMDALL | Config directory created
  ansible.builtin.file:
    path: "{{ heimdall_config_dir }}/config_bind_mount"
    state: directory
    mode: "0750"

- name: HEIMDALL | Environment file created
  ansible.builtin.file:
    path: "{{ heimdall_config_dir }}/heimdall.env"
    mode: "0640"
    state: touch
  changed_when: false

- name: HEIMDALL | Container running
  containers.podman.podman_container:
    name: "{{ heimdall_container_name }}"
    image: linuxserver/heimdall:latest
    state: started
    env_file: "{{ heimdall_config_dir }}/heimdall.env"
    restart_policy: on-failure:5
    env:
      TZ: "{{ timezone }}"
    ip: "{{ heimdall_internal_ip }}"
    volumes:
      - "{{ heimdall_config_dir }}/config_bind_mount:/config"

- name: HAPROXY | Systemd config deployed
  include: systemd.yml
  vars:
    service: "{{ heimdall_container_name }}"
