---

- name: PIHOLE | Config directories created
  ansible.builtin.file:
    path: "{{ pihole_config_dir }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - config_bind_mount
    - config_bind_mount/etc/pihole
    - config_bind_mount/etc/dnsmasq.d

- name: PIHOLE | Container running
  containers.podman.podman_container:
    name: "{{ pihole_container_name }}"
    image: pihole/pihole:latest
    restart_policy: on-failure:5
    log_level: "{{ pihole_log_level }}"
    log_driver: journald
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_web_password }}"
      PIHOLE_DNS_: "{{ pihole_upstream_dns }}"
      ServerIP: "{{ ansible_host }}"
      QUERY_LOGGING: "{{ pihole_query_logging }}"
    ip: "{{ pihole_internal_ip }}"
    volumes:
      - "{{ pihole_config_dir }}/config_bind_mount/etc/pihole:/etc/pihole"
      - "{{ pihole_config_dir }}/config_bind_mount/etc/dnsmasq.d:/etc/dnsmasq.d"

- name: PIHOLE | Systemd config deployed
  ansible.builtin.include: systemd.yml
  vars:
    service: "{{ pihole_container_name }}"
