---

- name: POSTGRES | Postgres allowed in ufw
  community.general.ufw:
    proto: tcp
    rule: allow
    to_port: "{{ postgres_port }}"
  when: ansible_facts.os_family == "Debian"

- name: POSTGRES | Postgres allowed in firewalld
  ansible.posix.firewalld:
    port: "{{ postgres_port }}/tcp"
    zone: "{{ firewalld_zone }}"
    immediate: true
    permanent: true
    state: enabled
  when: ansible_facts.os_family == "RedHat"

- name: POSTGRES | Config directory created
  ansible.builtin.file:
    path: "{{ postgres_config_dir }}/data_bind_mount"
    state: directory
    mode: "0750"

- name: POSTGRES | Environment file created
  ansible.builtin.file:
    dest: "{{ postgres_config_dir }}/postgres.env"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0640"
    state: touch
  changed_when: false

- name: POSTGRES | Container running
  containers.podman.podman_container:
    name: "{{ postgres_container_name }}"
    image: postgres:latest
    state: started
    env_file: "{{ postgres_config_dir }}/postgres.env"
    env:
      POSTGRES_PASSWORD: "{{ postgres_db_password }}"
      POSTGRES_USER: "{{ postgres_db_user }}"
      POSTGRES_DB: "{{ postgres_db_name }}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "{{ postgres_port }}:{{ postgres_port }}"
    ip: "{{ postgres_internal_ip }}"
    volumes:
      - "{{ postgres_config_dir }}/data_bind_mount:/var/lib/postgresql/data/pgdata"

- name: POSTGRES | Systemd config deployed
  block:
    - name: POSTGRES | Get container ID
      containers.podman.podman_container_info:
        name: postgres
      register: container_info

    - name: POSTGRES | Set fact for container ID
      set_fact:
        postgres_id: "{{ container_info.containers[0].Id }}"

    - name: POSTGRES | Systemd unit file deployed
      template:
        src: postgres/systemd/podman-postgres.service.j2
        dest: /etc/systemd/system/podman-{{ postgres_container_name }}.service
        seuser: system_u
        serole: object_r
        setype: systemd_unit_file_t
        mode: "0644"
        owner: root
        group: root

    - name: POSTGRES | Systemd service enabled
      systemd:
        name: podman-{{ postgres_container_name }}.service
        enabled: true
        masked: false
        daemon_reload: true
